### ISSUE TITLE
About training and validation data

### ISSUE THREAD

**Issue by young169** [Wanggcong/Spatial-Temporal-Re-identification#46]
I noticed that your default training command contains a '--train_all', and after preparing the market1501 dataset, it seems that train_all is made up of both train and val. Does that mean that the training data contains the validation data?

**Comment by young169** [comment]
And I also want to know how to set 'max_hist' in gen_st_model_market.py file, in case that I want to train this model on different datasets. An error happens about number exceeds. The id number may vary a lot, is it extendable to open-world scenes?

**Comment by Wanggcong** [comment]
> I noticed that your default training command contains a '--train_all', and after preparing the market1501 dataset, it seems that train_all is made up of both train and val. Does that mean that the training data contains the validation data?

Yes, '--train_all' means training a model with both "./train" and "val". In fact, the original training set is split into a training set and a validation set.

**Comment by Wanggcong** [comment]
> And I also want to know how to set 'max_hist' in gen_st_model_market.py file, in case that I want to train this model on different datasets. An error happens about number exceeds. The id number may vary a lot, is it extendable to open-world scenes?

"max_hist" denotes the histogram groups. It is determined by how long you collect a dataset.

**Comment by young169** [comment]
> > And I also want to know how to set 'max_hist' in gen_st_model_market.py file, in case that I want to train this model on different datasets. An error happens about number exceeds. The id number may vary a lot, is it extendable to open-world scenes?
> 
> "max_hist" denotes the histogram groups. It is determined by how long you collect a dataset.

Thank you for your reply, so the max_hist should be greater than the total time duration of collecting data right? defined in frame number or seconds? However, the index seem to exceed the bounds constantly.
And in the following line, what does this '8' mean?
###
Traceback (most recent call last):
  File "evaluate_st.py", line 191, in <module>
    ap_tmp, CMC_tmp = evaluate(query_feature[i],query_label[i],query_cam[i],query_frames[i], gallery_feature,gallery_label,gallery_cam,gallery_frames,distribution)
  File "evaluate_st.py", line 38, in evaluate
    pr = distribution[gc[i]-1][qc-1][hist_]
IndexError: index 10955 is out of bounds for axis 0 with size 10000

spatial_temporal_sum = np.zeros((class_num,8))                       
spatial_temporal_count = np.zeros((class_num,8))
###
